### ISSUE TITLE
Issue when running custom-built version of launchpad on ubuntu 20.04

### ISSUE THREAD

**Issue by dennisrijsdijk** [net-core-audio/launchpad#2]
/home/dennis/RiderProjects/LaunchpadMacroDeluxe/bin/Debug/netcoreapp3.1/LaunchpadMacroDeluxe
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'PortMidi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'PortMidi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Launchpad.LaunchpadManager.FindDevice()
   at LaunchpadMacroDeluxe.Program.Main(String[] args) in /home/dennis/RiderProjects/LaunchpadMacroDeluxe/Program.cs:line 14

After compiling the Launchpad library and adding the dll as a reference in Rider, I get the above error when running the application.

**Comment by peacecwz** [comment]
Hi @dennisrijsdijk I think nuget package is missing or version mismatch with new .NET Core versions. I will test it with new .NET Core versions. Can you add more details your systems like OS, .NET SDK Version, .NET Runtime version, Rider version vs

**Comment by dennisrijsdijk** [comment]
sorry, just now see this, yay to no notifications... Dotnet (core) 5, Ubuntu 20.04 LTS, rider 2021.1
